
<div class="dashboard-tabs-nav">
    <ul class="nav nav-tabs megatab-nav dashboard" id="myTab">
        <li class="uploads-tab">
            <a href="/weblogs">
                <div class="megatab-content clearfix">
                    <h2 class="megatab-title"><i class="icon icon-cloud-upload"></i> General Logs</h2>
                    <div class="stats">
                        <div class="stat unknown">
                            Pending
                            <span class="badge badge-warning">23</span>
                        </div>
                        <div class="stat unknown">
                            Pending
                            <span class="badge badge-warning">23</span>
                        </div>
                    </div>
                </div>
            </a>
        </li>
        <li class="for-approval-tab active">
            <a href="#">
                <div class="megatab-content clearfix">
                    <h2 class="megatab-title"><i class="icon icon-thumbs-up"></i> Failed Login</h2>
                    <div class="stats">
                        <div class="stat unknown">
                            Pending
                            <span class="badge badge-warning">23</span>
                        </div>
                        <div class="stat unknown">
                            Pending
                            <span class="badge badge-warning">23</span>
                        </div>
                    </div>
                </div>
            </a>
        </li>
    </ul>
</div>

<div class="dashboard-tabs">
    <div class="tab-content dashboard">
        <div class="tab-pane fade in" id="uploads-tab">
            NONE
        </div>
        <div class="tab-pane fade active in" id="for-approval-tab">
            <div class="clearfix" style="margin-top:20px">
                <div id="get" class="form-search">
                    <form id="search-form" method="get">        
                        <input id="pg-hidden" type="hidden" name="pg" value="1"/>
                        <input id="sort-col-hidden" type="hidden" name="sortcol" value="id"/>
                        <input id="sort-val-hidden" type="hidden" name="sortval" value="DESC"/>
                        <input id="log-type-hidden" type="hidden" name="logtype" value="failed_login"/>
                        <input id="report-name-hidden" type="hidden" name="report-name-hidden" value="weblogs"/>
                        <div class="col-xs-3">
                            <div class="input-group">
                                <input type="user/search" id="search-text-input" name="search" placeholder="Search Text" class="form-control">
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="icon-search"></i> Search</button>
                                </div><!-- /btn-group -->
                            </div><!-- /input-group -->
                        </div>
                    </form>
                </div>

                <div class="pull-right" style="margin-top:-20px;">                

                    <div id="pagination-div" class="clearfix">                    
                        <ul id="pagination-ul" class="pagination">                        
                        </ul>
                    </div>
                </div>    
            </div>
            <div class="">
                <table class="table table-striped table-hover">
                    <thead id="search-thead">
                        <tr>                         
                            <th>ID</th>
                            <th>Date Created</th>
                            <th>Username</th>
                            <th>IP Address</th>
                            <th>URL</th>
                            <th>Post Data</th>
                            <th>Notes</th>
                            <th>Event Status</th>
                            <th>Controller</th>
                            <th>Action</th>
                            <th>Source</th>
                            <th>Log Type</th>
                        </tr>
                    </thead>
                    <tbody id="search-tbody">
                    </tbody>
                </table>  
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("#search-form").submit();
    });

</script>

