<div class="content-panel ">
    <h2 class="page-header">WEB LOGS</h2>    
    <div class="dashboard-tabs-nav">
        <ul class="nav nav-tabs megatab-nav dashboard" id="myTab">
            <li class="uploads-tab <?php if (is_null($data['showTab'])) { echo "active"; }?>">
                <a href="/weblogs">
                    <div class="megatab-content clearfix">
                        <h2 class="megatab-title"><i class="icon icon-bar"></i> General Logs</h2>
                    </div>
                </a>
            </li>
            <li class="uploads-tab <?php if ($data['showTab']== 'failed_login') { echo "active"; }?>">
                <a href="/weblogs?show=failed_login">
                    <div class="megatab-content clearfix">
                        <h2 class="megatab-title"><i class="icon icon-thumbs-down"></i> Failed Login</h2>
                    </div>
                </a>
            </li>
            <li class="uploads-tab <?php if ($data['showTab']== 'account_lockout') { echo "active"; }?>">
                <a href="/weblogs?show=account_lockout">
                    <div class="megatab-content clearfix">
                        <h2 class="megatab-title"><i class="icon icon-exclamation-triangle"></i> Account Lockout</h2>

                    </div>
                </a>
            </li>
            <li class="uploads-tab <?php if ($data['showTab']== 'successful_login') { echo "active"; }?>">
                <a href="/weblogs?show=successful_login">
                    <div class="megatab-content clearfix">
                        <h2 class="megatab-title"><i class="icon icon-thumbs-up"></i> Successful Login</h2>

                    </div>
                </a>
            </li>
            <li class="uploads-tab <?php if ($data['showTab']== 'user_add') { echo "active"; }?>">
                <a href="/weblogs?show=user_add">
                    <div class="megatab-content clearfix">
                        <h2 class="megatab-title"><i class="icon icon-bar"></i> User Logs</h2>

                    </div>
                </a>
            </li>
            <li class="uploads-tab <?php if ($data['showTab']== 'role_add') { echo "active"; }?>">
                <a href="/weblogs?show=role_add">
                    <div class="megatab-content clearfix">
                        <h2 class="megatab-title"><i class="icon icon-bar"></i> Role Logs</h2>

                    </div>
                </a>
            </li>
            <li class="uploads-tab <?php if ($data['showTab']== 'page_add') { echo "active"; }?>">
                <a href="/weblogs?show=page_add">
                    <div class="megatab-content clearfix">
                        <h2 class="megatab-title"><i class="icon icon-bar"></i> Page Logs</h2>

                    </div>
                </a>
            </li>
            <li class="uploads-tab <?php if ($data['showTab']== 'option_update') { echo "active"; }?>">
                <a href="/weblogs?show=option_update">
                    <div class="megatab-content clearfix">
                        <h2 class="megatab-title"><i class="icon icon-bar"></i> Option Logs</h2>

                    </div>
                </a>
            </li>
            <li class="uploads-tab <?php if ($data['showTab']== 'password_reset') { echo "active"; }?>">
                <a href="/weblogs?show=password_reset">
                    <div class="megatab-content clearfix">
                        <h2 class="megatab-title"><i class="icon icon-bar"></i> Password Reset</h2>

                    </div>
                </a>
            </li>
        </ul>
    </div>

    
    <div class="dashboard-tabs">
        <div class="tab-content dashboard">
            <div class="tab-pane fade active in" id="uploads-tab">
                <div class="clearfix" style="margin-top:20px">
                    <div id="get" class="form-search">
                        <form id="search-form" method="get">        
                            <input id="pg-hidden" type="hidden" name="pg" value="1"/>
                            <input id="sort-col-hidden" type="hidden" name="sortcol" value="username"/>
                            <input id="sort-val-hidden" type="hidden" name="sortval" value="DESC"/>
                            <input id="log-type-hidden" type="hidden" name="logtype" value="<?php echo $data['showTab'];?>"/>
                            <input id="report-name-hidden" type="hidden" name="report-name-hidden" value="weblogs"/>
                            <div class="col-xs-3">
                                <div class="input-group">
                                    <input type="user/search" id="search-text-input" name="search" placeholder="Search Text" class="form-control">
                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-default"><i class="icon-search"></i> Search</button>
                                    </div><!-- /btn-group -->
                                </div><!-- /input-group -->
                            </div>
                        </form>
                    </div>

                    <div class="pull-right" style="margin-top:-20px;">                

                        <div id="pagination-div" class="clearfix">                    
                            <ul id="pagination-ul" class="pagination">                        
                            </ul>
                        </div>
                    </div>    
                </div>
       
                <?php if($data['showTab']== 'user_add') :?>
                <div class="wide-table">
                    <table class="table table-striped table-hover">
                        <thead id="search-thead">
                            <tr>                         
                                <th>Date Created</th>
                                <th>Username</th>
                                <th>Post Data</th>
                                <th>Log Type</th>
                            </tr>
                        </thead>
                        <tbody id="search-tbody">
                        </tbody>
                    </table>  
                </div>
                
                <?php elseif($data['showTab']== 'role_add') :?>  
                <div class="wide-table">
                    <table class="table table-striped table-hover">
                        <thead id="search-thead">
                            <tr>                         
                                <th>Date Created</th>
                                <th>Username</th>
                                <th>Post Data</th>
                                <th>Log Type</th>
                            </tr>
                        </thead>
                        <tbody id="search-tbody">
                        </tbody>
                    </table>  
                </div>
                
                <?php elseif($data['showTab']== 'page_add') :?>
                <div class="wide-table">
                    <table class="table table-striped table-hover">
                        <thead id="search-thead">
                            <tr>                         
                                <th>Date Created</th>
                                <th>Username</th>
                                <th>Post Data</th>
                                <th>Log Type</th>
                            </tr>
                        </thead>
                        <tbody id="search-tbody">
                        </tbody>
                    </table>  
                </div>
                
                <?php elseif($data['showTab']== 'option_update') :?>
                <div class="wide-table">
                    <table class="table table-striped table-hover">
                        <thead id="search-thead">
                            <tr>                         
                                <th>Date Created</th>
                                <th>Username</th>
                                <th>Post Data</th>
                                <th>Log Type</th>
                            </tr>
                        </thead>
                        <tbody id="search-tbody">
                        </tbody>
                    </table>  
                </div>
                
                <?php elseif($data['showTab']== 'password_reset') :?>        
                <div class="wide-table">
                    <table class="table table-striped table-hover">
                        <thead id="search-thead">
                            <tr>                         
                                <th>Date Created</th>
                                <th>Username</th>
                                <th>Post Data</th>
                                <th>Log Type</th>
                            </tr>
                        </thead>
                        <tbody id="search-tbody">
                        </tbody>
                    </table>  
                </div>
                
                <?php else : ?>
                <div class="wide-table">
                    <table class="table table-striped table-hover">
                        <thead id="search-thead">
                            <tr>                         
                                <th>ID</th>
                                <th>Date Created</th>
                                <th>Username</th>
                                <th>IP Address</th>
                                <th>URL</th>
                                <th>Post Data</th>
                                <th>Notes</th>
                                <th>Event Status</th>
                                <th>Controller</th>
                                <th>Action</th>
                                <th>Source</th>
                                <th>Log Type</th>
                            </tr>
                        </thead>
                        <tbody id="search-tbody">
                        </tbody>
                    </table>  
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("#search-form").submit();
    });

$('input#search-text-input').bind('input', function() {
        var c = this.selectionStart,
                r = /[^a-z0-9 _]/gi,
                v = $(this).val();
        if (r.test(v)) {
            $(this).val(v.replace(r, ''));
            c--;
        }
        this.setSelectionRange(c, c);
    });
    
    $(".nav.megatab-nav li").css({
        //"min-width" : "200px"
        "min-width" : "130px"
    });
    
    $(".nav.megatab-nav li a").css({
        "box-shadow" : "0px 0px 0px rgba(0,0,0,1)",
        "border-color" : "#34495e",
        "border-width" : "1px 1px 1px 1px",        
        "border-radius" : "4px 4px 0 0",
        "padding-bottom" : "0px",
        "margin-bottom" : "0px",
    });
    
    $(".dashboard-tabs").css({        
        "border-color" : "#34495e",
        "border-width" : "1px 1px 1px 1px",
        "border-style" : "solid"
    });
    $(".megatab-content .megatab-title").css({
        "font-size" : "1.1em"
    });
    $(".nav.megatab-nav li").css({
        "margin-right" : "1px"
    });
    $(".tab-content.dashboard .tab-pane#uploads-tab.active").css({
        "border-top-color" : "transparent"
    });
    
</script>

