<div class="content-panel ">
    <h2 class="page-header">Create New Role</h2>
    <form class="form-horizontal" id="tableForm" name="tableForm" method="POST" action="/roles/add">
        <input type="hidden" id="date_created" name="date_created" value="" />
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Role Name</label>
            <div class="col-xs-3">
                <input type="text" class="form-control" id="role" name="role" placeholder="Enter role name here.." required="">
            </div>
        </div>               
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Status</label>
            <div class="col-xs-3">
                <select name="status" required="">
                    <option value="ACTIVE">Active</option>
                    <option value="INACTIVE">Inactive</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="access" class="col-xs-2 control-label">Access</label>
            <div class="col-xs-10">
                <div class="row">

                    <?php
                    $prevGroup = '';
                    foreach ($allpages as $access) {
                        $selected = '';

                        if ($access->controller != $prevGroup) {
                            $groupName = strtolower(str_replace(' ', '', $access->controller));

                            echo "</div><div class='row-group row-group-{$groupName} clearfix' data-cb-class='.cb-{$groupName}'>";
                            echo "<h4>" . $access->controller . " <small><a onclick='checkAll(\"{$groupName}\")' class='check-group'>Check All </a> / <a onclick='uncheckAll(\"{$groupName}\")' class='uncheck-group'>Uncheck All </a></small></h4>";

                            $prevGroup = $access->controller;
                        }
                        
                        ?>


                        <div class="col-xs-6">
                            <div class="checkbox" style="overflow: hidden">
                                <label for="role-<?php echo $access->id ?>">
                                    <input class="cb-<?php echo strtolower(str_replace(' ', '', $access->controller)) ?>" type="checkbox" name="access[]" id="role-<?php echo $access->id ?>" value="<?php echo $access->id ?>" >
                                    <?php echo $access->pagename;?>
                                </label>
                            </div>
                        </div>
                        <?php
                    }
                    ?>
                </div>
            </div>
        </div>
        <div class="col-lg-offset-2">
            <a href="/roles"  class="btn btn-default">Cancel </a>
            <input type="reset" value="Reset"  class="btn btn-default">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

<script type="text/javascript">
    window.onload = display_c();

    function display_c(){
        var refresh=1000; // Refresh rate in milli seconds
        mytime=setTimeout('display_ct()',refresh)
    }

    function display_ct() {
        var strcount;
        var x = new Date();
        var mm = x.getMonth()+1;
        mm = (mm < 10 ? "0"+mm : mm);
        var dd = (x.getDate() < 10 ? "0"+x.getDate() : x.getDate());
        var yyyy = x.getFullYear();
        var hh = (x.getHours() < 10 ? "0"+x.getHours() : x.getHours());
        var ii = (x.getMinutes() < 10 ? "0"+x.getMinutes() : x.getMinutes());
        var ss = (x.getSeconds() < 10 ? "0"+x.getSeconds() : x.getSeconds());

        var date = yyyy + "-" + mm + "-" + dd;
        var time = hh + ":" + ii + ":" + ss;
        var display = date + " " + time;

        document.getElementById('date_created').value = display;
        tt=display_c();
    }

    function checkAll(groupName){
        var classname = "cb-" + groupName;
        $("input:checkbox."+classname).prop('checked', true);
    }
    
    function uncheckAll(groupName){
        var classname = "cb-" + groupName;
        $("input:checkbox."+classname).prop('checked', false);
    }
    
    jQuery.validator.addMethod(
            "regexmeta",
            function(value, element, regexp) {
                var re = new RegExp('^[a-zA-Z0-9-_ ]+$');
                return this.optional(element) || re.test(value);
            },
            "Value should only be letters and numbers only."
            );

$("#tableForm").validate({
        errorClass: 'has-error',
        validClass: 'has-success',
        errorElement: 'span',
        highlight: function(element, errorClass, validClass) {
            $(element).parents("div.form-group").addClass(errorClass).removeClass(validClass);

        },
        unhighlight: function(element, errorClass, validClass) {
            $(element).parents(".form-group.has-error").removeClass(errorClass).addClass(validClass);
        },
        rules: {
            role: {
                regexmeta: "dummy",
                maxlength: 200
            }
           

        }
    });
</script>