<div class="content-panel ">
    <h2 class="page-header">Pay List</h2>
    <div class="page-content" style="">
    <div class="clearfix">                      
        <a class="btn btn-primary pull-left" href="/pay/createpay" style="margin-right:10px;">
            <i class="icon-plus"></i>
            Create Pay
        </a>
        
    </div>
    <br/>
    <div class="wide-table">
            <table class="table table-striped table-hover">
                <thead id="search-thead">
                    <tr>    
                        <th>Pay ID</th>
                        <th>Employee</th>
                        <th>Year</th>
                        <th>Month</th>
                        <th>Pay Period</th>
                        <th>Days of work</th>
                        <th>Adjust Pay</th>
                        <th>Payslip Action</th>                        
                    </tr>
                </thead>
                <tbody id="search-tbody">
                <?php 
                    foreach($data as $row){                         
                        $payPeriod = "";
                        if($row['pay_period']==1){
                            $payPeriod.=" 1 to 15";
                        }
                        else{
                            $lastDay = date("d", mktime(0, 0, 0, $row['month']+1,0,date("Y")));

                            $payPeriod.= " 16 to ".$lastDay;
                        }
                ?>
                    <tr>     
                        <td><?php echo $row['id'] ?></td>
                        <td><?php echo $row['last_name'].", ".$row['first_name'] ?></td>
                        <td><?php echo $row['year'] ?></td>
                        <td><?php echo date('F', mktime(0, 0, 0, $row['month'], 10)) ?> </td>
                        <td><?php echo $payPeriod ?></td>
                        <td><?php echo $row['days_of_work'] ?></td>
                        <td>
                            <a href="/pay/addot?id=<?php echo $row['id']?>">Add Overtime </a>| 
                            <a href="/pay/addut?id=<?php echo $row['id']?>">Add Undertime </a>| 
                            <a href="/pay/addallowance?id=<?php echo $row['id']?>">Add Allowance </a> |
                            <a href="/pay/adddeduction?id=<?php echo $row['id']?>">Add Deduction </a> 
                        <td>
                            <a href="/pay/preview?id=<?php echo $row['id']?>">Preview Payslip</a> | 
                            <a href="/pay/generate?id=<?php echo $row['id']?>">Generate Payslip</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>  
        </div>
    </div>
</div>

<script type="text/javascript">
  
$('input#search-text-input').bind('input', function() {
        var c = this.selectionStart,
                r = /[^a-z0-9 _]/gi,
                v = $(this).val();
        if (r.test(v)) {
            $(this).val(v.replace(r, ''));
            c--;
        }
        this.setSelectionRange(c, c);
    });
</script>
