<div class="content-panel ">
    <!--<h2 class="page-header">Create New User</h2>-->        

    <form class="form-horizontal" id="tableForm" name="tableForm" method="POST" action="/user/add">        
<h2 class="page-header">
    <?php if(isset($data['id'])) { 
        echo "Payslip Details";
    }else {
        echo "Payslip PREVIEW";
    }
?>
        
</h2>

<h4 class="page-header">Payslip information </h4>
        <?php if(isset($data['id'])) { ?>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Payslip ID</label>
            <div class="col-xs-3">
                <h4><?php echo $data['id'] ?></h4>
            </div>
        </div>
        <?php } ?>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Employee Number</label>
            <div class="col-xs-3">
                <h4><?php echo $data['employee_number'] ?></h4>
            </div>
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Name</label>
            <div class="col-xs-3">
                <h4><?php echo $data['name'] ?></h4>
            </div>
        </div>        

        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Pay Period</label>
            <div class="col-xs-3">
                <h4><?php echo $data['pay_period'] ?></h4>
            </div>
        </div>
<h4 class="page-header">Regular Wage</h4>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Days of work</label>
            <div class="col-xs-3">
                <h4><?php echo $data['days_of_work'] ?></h4>
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Daily Rate</label>
            <div class="col-xs-3">
                <h4><?php echo number_format($data['daily_rate'],2) ?></h4>
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Total Regular Wage</label>
            <div class="col-xs-3">
                <h4><b><?php echo number_format($data['total_regular_wage'],2) ?></b></h4>
            </div>
        </div>
<?php if(count($data['overtime'])>0) {?>
<h4 class="page-header">Overtime</h4>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Overtime entries</label>
            <div class="col-xs-7">
                <table class="table table-striped table-hover">
            <thead id="search-thead">
                <tr>                        
                    <th>Overtime Type</th>
                    <th>Number of hours</th>
                    <th>Overtime Pay</th>                    
                </tr>
            </thead>
            <tbody id="search-tbody">
                <?php foreach($data['overtime'] as $row){ ?>
                <tr>
                    <td><?php echo $row['ot_type']?></td>
                    <td><?php echo number_format($row['hours'],2)?></td>
                    <td><?php echo number_format($row['total_pay'],2)?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
            </div>
        </div>
        
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Total Overtime Pay</label>
            <div class="col-xs-3">
                <h4><b><?php echo number_format($data['total_overtime'],2) ?></b></h4>
            </div>
        </div>
<?php } ?>
<?php if($data['total_govt']>0){ ?>
<h4 class="page-header">Government contributions</h4>
        
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">SSS</label>
            <div class="col-xs-3">
                <h4><?php echo number_format($data['sss'],2) ?></h4>
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Philhealth</label>
            <div class="col-xs-3">
                <h4><?php echo number_format($data['philhealth'],2) ?></h4>
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">HDMF</label>
            <div class="col-xs-3">
                <h4><?php echo number_format($data['hdmf'],2) ?></h4>
            </div>
        </div>       
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Total contributions</label>
            <div class="col-xs-3">
                <h4><b><?php echo number_format($data['total_govt'],2) ?></b></h4>
            </div>
        </div>       
<?php } ?>
<?php if(count($data['undertime'])>0) {?>
<h4 class="page-header">Undertime</h4>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Undertime entries</label>
            <div class="col-xs-7">
                <table class="table table-striped table-hover">
            <thead id="search-thead">
                <tr>                                            
                    <th>Number of hours</th>
                    <th>Deduction</th>                    
                </tr>
            </thead>
            <tbody id="search-tbody">
                <?php foreach($data['undertime'] as $row){ ?>
                <tr>
                    <td><?php echo number_format($row['hours'],2)?></td>
                    <td><?php echo number_format($row['total_ut'],2)?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
            </div>
        </div>
        
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Total Deductions</label>
            <div class="col-xs-3">
                <h4><b><?php echo number_format($data['total_undertime'],2) ?></b></h4>
            </div>
        </div>
<?php } ?>
<h4 class="page-header">Tax</h4>

        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Total Taxable Income</label>
            <div class="col-xs-3">
                <h4><?php echo number_format($data['taxable'],2) ?></h4>
            </div>
        </div>
<div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Income tax</label>
            <div class="col-xs-3">
                <h4><?php echo number_format($data['tax'],2) ?></h4>
            </div>
        </div>
<?php if(count($data['allowance'])>0) {?>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Non-taxable Allowances</label>
            <div class="col-xs-7">
                <table class="table table-striped table-hover">
            <thead id="search-thead">
                <tr>                                            
                    <th>Type</th>
                    <th>Amount</th>                    
                </tr>
            </thead>
            <tbody id="search-tbody">
                <?php foreach($data['allowance'] as $row){ ?>
                <tr>
                    <td><?php echo $row['type'] ?></td>
                    <td><?php echo number_format($row['amount'],2)?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
            </div>
        </div>
        
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Total Non-taxable</label>
            <div class="col-xs-3">
                <h4><b><?php echo number_format($data['total_allowance'],2) ?></b></h4>
            </div>
        </div>
<?php } ?>
        <div class="form-group">
            <label for="start_date" class="col-xs-2 control-label"><h3><b>Net Income</b></h3></label>
            <div class="col-xs-3">
                <h3><b><?php echo number_format($data['net_income'],2) ?></b></h3>
            </div>
        </div>     

        <div class="col-lg-offset-2">
            <?php if(isset($mypayslip)) { ?>
            <a href="/pay/mypayslips"  class="btn btn-primary">Back </a>
            <?php }else{ ?>
            <a href="/pay/paysliplist"  class="btn btn-primary">Back </a>
            <?php } ?>
        </div>
    </form>
</div>

<?php
$dateplus30 = date("Y-m-d", strtotime("+30 days", time()));
$conf = $this->Conf_widget();
?>


<script type="text/javascript">
    
    $(function() {
        $( "#date_hired" ).datepicker();        
    });
    
    $(function() {
        $("#pwd_exp_date").datepicker();
        $("#pwd_exp_date").datepicker("setDate", "<?php echo $dateplus30; ?>");
        $("#pwd_exp_date").datepicker("option", "dateFormat", "yy-mm-dd");
    });

	/*$('#email').blur(function(){
		var emailreg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
		var emailadd = $('#email').val();
		var URL = '/user/checkemail';
		var dataString = 'email=' + emailadd;

			if(!emailreg.test(emailadd)){
				$("#emailspan").html('<font color="#cc0000">Please enter valid Email address</font>');
				$("#submit").prop("disabled", true);
			}else{
				$("#emailspan").html('<font color="#cc0000"></font>');
				$("#submit").prop("disabled", false);
			}

		$.ajax({
			type: "POST",
			url: URL,
			data: dataString,
			cache: false,
			success: function(resp) {
			  if (resp != 0){
				$("#emailspan").html('<font color="#cc0000">Email address is already in use.</font>');
				$("#submit").prop("disabled", true);
			  }else{
			  }

			}
		});

	});
    */

    jQuery.validator.addMethod("notEqual", function(value, element, param) {
        return this.optional(element) || value != $(param).val();
    }, "Username and Password should be different");

    jQuery.validator.addMethod('username_check', function(value) {
        var resp = username_check(value);
        if (resp == 0) {
            return true;
        } else {
            return false;
        }
    }, "Username already exists");

    jQuery.validator.addMethod(
            "regex",
            function(value, element, regexp) {
                var re = new RegExp(<?php echo $conf['pwd_regexp']; ?>);
                return this.optional(element) || re.test(value);
            },
            "Password should contain atleast one lowercase or uppercase letter, or number, or characters like !@#$%^& "
            );


    jQuery.validator.addMethod(
            "regexmeta",
            function(value, element, regexp) {
                var re = new RegExp('^[a-zA-Z0-9-_ ]+$');
                return this.optional(element) || re.test(value);
            },
            "Value should only be letters and numbers only."
            );

    $("#tableForm").validate({
        errorClass: 'has-error',
        validClass: 'has-success',
        errorElement: 'span',
        highlight: function(element, errorClass, validClass) {
            $(element).parents("div.form-group").addClass(errorClass).removeClass(validClass);
        },
        unhighlight: function(element, errorClass, validClass) {
            $(element).parents(".form-group.has-error").removeClass(errorClass).addClass(validClass);
        },
        rules: {
            password: {
                minlength: <?php echo $conf['password_length']; ?>,
                notEqual: "#username",
                regex: "dummy"


            },
            password_confirm: {
                equalTo: "#password"
            },
            username: {
                maxlength: 30,
                username_check: "dummy",
                regexmeta: "dummy"
            }

        }
    });

    //$('#username').keyup(username_check);
    function username_check(username) {

        if (username == '') {
            return 0;
        } else {

            var ajaxResponse;

            jQuery.ajax({
                async: false,
                type: 'GET',
                url: '/user/checkusername',
                data: 'username=' + username,
                cache: false,
                success: function(response) {
                    ajaxResponse = response;
                }
            });
            return ajaxResponse;
        }
    }



if ($.browser.webkit) {
    $('input[name="password"]').attr('autocomplete', 'off');
    $('input[name="username"]').attr('autocomplete', 'off');
}


</script>