<div class="content-panel ">
    <h2 class="page-header">
        Payslip Report
    </h2>
    <div class="page-content" style="">
    <form class="form-horizontal" id="tableForm" name="tableForm" method="POST">
<!--        <input type="hidden" id="id" name="id" value="" />-->
             <div class="form-group">
            <label for="gender" class="col-xs-2 control-label">Filter by Pay Period</label>
            <div class="col-xs-3">
                <select name="pay_period" required="" style="width:300px;">
                    <option value="All">All</option>
                        <?php                         
                        foreach($pay_periods as $period){ 
                            $selected = "";
                            if($period['pay_period']==$selected_pay_period) $selected = "selected=\"\"";
                        ?>
                        <option value="<?php echo $period['pay_period'] ?>" <?php echo $selected ?>><?php echo $period['pay_period'] ?></option>
                        <?php } ?>                        
                </select>
            </div>
            <div class="col-xs-3">
               <button type="submit" class="btn btn-primary btn-xs">Submit</button>
            </div>
        </div>        
    </form>
    <div class="wide-table">
            <table class="table table-striped table-hover">
                <thead id="search-thead">
                    <tr>    
                        <th>Payslip</th>
                        <th>Employee</th>                        
                        <th>Pay Period</th>
                        <th>Regular Wage</th> 
                        <th>Overtime</th> 
                        <th>Allowance</th> 
                        <th>Undertime</th> `
                        <th>Deduction</th>                         
                        <th>Govt Contribution</th> 
                        <th>Net Pay</th> 
                    </tr>
                </thead>
                <tbody id="search-tbody">
                <?php 
                    $grand_total_regular = 0;
                    $grand_total_allowance = 0;
                    $grand_total_overtime = 0;
                    $grand_total_undertime = 0;
                    $grand_total_deduction = 0;
                    $grand_total_govt = 0;
                    $grand_total_net = 0;
                    foreach($data as $row){
                        $grand_total_allowance += $row['total_allowance'];
                        $grand_total_deduction += $row['total_deduction'];
                        $grand_total_govt += $row['total_govt'];
                        $grand_total_net += $row['net_income'];
                        $grand_total_overtime += $row['total_overtime'];
                        $grand_total_regular += $row['total_regular_wage'];
                        $grand_total_undertime += $row['total_undertime'];
                ?>
                    <tr>     
                        <td><?php echo $row['id'] ?></td>
                        <td><?php echo $row['name'] ?></td>                        
                        <td><?php echo $row['pay_period'] ?></td>                        
                        <td><?php echo number_format($row['total_regular_wage'],2) ?></td>
                        <td><?php echo number_format($row['total_overtime'],2) ?></td>
                        <td><?php echo number_format($row['total_allowance'],2) ?></td>
                        <td><?php echo number_format($row['total_undertime'],2) ?></td>
                        <td><?php echo number_format($row['total_deduction'],2) ?></td>
                        <td><?php echo number_format($row['total_govt'],2) ?></td>
                        <td><?php echo number_format($row['net_income'],2) ?></td>
                    </tr>
                <?php } ?>
                    <tr>
                        <td colspan="3" align="center"><b>Total</b></td>
<!--                        <td>&nbsp;</td>
                        <td>&nbsp;</td>-->
                        <td><b><?php echo number_format($grand_total_regular,2) ?></b></td>
                        <td><b><?php echo number_format($grand_total_overtime,2) ?></b></td>
                        <td><b><?php echo number_format($grand_total_allowance,2) ?></b></td>
                        <td><b><?php echo number_format($grand_total_undertime,2) ?></b></td>
                        <td><b><?php echo number_format($grand_total_deduction,2) ?></b></td>
                        <td><b><?php echo number_format($grand_total_govt,2) ?></b></td>
                        <td><b><?php echo number_format($grand_total_net,2) ?></b></td>
                    </tr>
                </tbody>
            </table>  
        </div>
    </div>
</div>

<script type="text/javascript">
  
//$('input#search-text-input').bind('input', function() {
//        var c = this.selectionStart,
//                r = /[^a-z0-9 _]/gi,
//                v = $(this).val();
//        if (r.test(v)) {
//            $(this).val(v.replace(r, ''));
//            c--;
//        }
//        this.setSelectionRange(c, c);
//    });
</script>
