<div class="content-panel ">
    <h2 class="page-header">SSS Reference Table</h2>
    <div class="page-content" style="">
    <div class="clearfix">                      

        <div class="wide-table">
            <table class="table table-striped table-hover">
                <thead id="search-thead">
                    <tr>                        
                        <th>Compensation Level</th>
                        <th>Monthly Salary Credit</th>
                        <th>Total Contribution (Pesos)</th>
                        <!--<th>Action</th>-->
                    </tr>
                </thead>
                <tbody id="search-tbody">
                <?php foreach($data as $row){ ?>
                    <tr>                        
                        <td><?php echo $row['compensation_level'] ?></td>
                        <td><?php echo $row['monthly_salary_credit'] ?></td>
                        <td><?php echo $row['total_contribution'] ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>  
        </div>
    </div>
    </div>
</div>

<script type="text/javascript">
  
$('input#search-text-input').bind('input', function() {
        var c = this.selectionStart,
                r = /[^a-z0-9 _]/gi,
                v = $(this).val();
        if (r.test(v)) {
            $(this).val(v.replace(r, ''));
            c--;
        }
        this.setSelectionRange(c, c);
    });
</script>
