<div class="content-panel ">
    <h2 class="page-header">Employee Information</h2>

    <div style="clear:both">
        <div class="col-xs-2" style="font-weight: bold;">First Name</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->first_name) ? $employee->first_name : ''; ?>
        </div>
    </div>
    <div style="clear:both">
        <div class="col-xs-2" style="font-weight: bold;">Middle Name</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->middle_name) ? $employee->middle_name : ''; ?>
        </div>
    </div>
    <div style="clear:both">
        <div class="col-xs-2" style="font-weight: bold;">Last Name</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->last_name) ? $employee->last_name : ''; ?>
        </div>
    </div>
    <div style="clear:both">
        <div class="col-xs-2" style="font-weight: bold;">Gender</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->gender) ? $employee->gender : ''; ?>
        </div>
    </div>
    <div style="clear:both">
        <div class="col-xs-2" style="font-weight: bold;">Nick Name</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->nickname) ? $employee->nickname : ''; ?>
        </div>
    </div>
    <div style="clear:both">
        <div class="col-xs-2" style="font-weight: bold;">Employment Status</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->employment_status) ? $employee->employment_status : ''; ?>
        </div>
    </div>
    <div style="clear:both">

        <div class="col-xs-2" style="font-weight: bold;">Date Hired</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->date_hired) ? $employee->date_hired : ''; ?>
        </div>
    </div>
    <div style="clear:both">

        <div class="col-xs-2" style="font-weight: bold;">Group</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->group) ? $employee->group : ''; ?>
        </div>
    </div>
    <div style="clear:both">

        <div class="col-xs-2" style="font-weight: bold;">Role</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->role) ? $employee->role : ''; ?>
        </div>
    </div>
    <div style="clear:both">

        <div class="col-xs-2" style="font-weight: bold;">Shift</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->shift) ? $employee->shift : ''; ?>
        </div>
    </div>
    <div style="clear:both">

        <div class="col-xs-2" style="font-weight: bold;">Personal Email</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->personal_email) ? $employee->personal_email : ''; ?>
        </div>
    </div>
    <div style="clear:both">

        <div class="col-xs-2" style="font-weight: bold;">Company Email</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->company_email) ? $employee->company_email : ''; ?>
        </div>
    </div>
    <div style="clear:both">

        <div class="col-xs-2" style="font-weight: bold;">Address</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->address) ? $employee->address : ''; ?>
        </div>
    </div>
    <div style="clear:both">

        <div class="col-xs-2" style="font-weight: bold;">Telephone</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->telephone) ? $employee->telephone : ''; ?>
        </div>
    </div>
    <div style="clear:both">

        <div class="col-xs-2" style="font-weight: bold;">Mobile</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->mobile) ? $employee->mobile : ''; ?>
        </div>
    </div>
    <div style="clear:both">

        <div class="col-xs-2" style="font-weight: bold;">Emergency Contact Name</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->emergency_contact_name) ? $employee->emergency_contact_name : ''; ?>
        </div>
    </div>
    <div style="clear:both">

        <div class="col-xs-2" style="font-weight: bold;">Emergency Contact Phone</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->emergency_contact_phone) ? $employee->emergency_contact_phone : ''; ?>
        </div>
    </div>
    <div style="clear:both">

        <div class="col-xs-2" style="font-weight: bold;">Salary</div>
        <div class="col-xs-3">
            <?php echo !empty($employee->salary) ? $employee->salary : ''; ?>
        </div>
    </div>

</div>