<div class="content-panel ">
  <h2 class="page-header">Bulk Create Holiday</h2>
  
  <div class="page-content">

    <div class="alert alert-info">
      <h2>Instructions</h2>
      Required Columns: <strong>date, holiday, proclamation, rate</strong>
      <br /><br />
      <strong>Proclamation</strong> value should be <strong>'Special Non-Working'</strong> or <strong>'Regular'</strong> only.
    </div>

    <?php  
      if (!empty($data['saveMessages']['success'])){
        echo ' <div class="alert alert-success">';
        echo ' <h2>Successfully Created Holiday/s</h2>';
        foreach($data['saveMessages']['success'] as $message){
          echo "<li>$message</li>";
        }
        echo "</div>";
      }
    ?>
    <?php 
      if (!empty($data['saveMessages']['failed'])){
        echo ' <div class="alert alert-danger">';
        echo ' <h2>Failed to Created Holiday/s</h2>';
        foreach($data['saveMessages']['failed'] as $message){
          echo "<li>$message</li>";
        }
        echo "</div>";
      }
    ?>

    <form class="form-horizontal" id="tableForm" name="tableForm" method="POST" enctype="multipart/form-data" action="">
      <div class="form-group">
        <label for="file" class="col-xs-2 control-label">CSV File</label>
        <div class="col-xs-3">
          <input type="file" name="file" id="file" required><br>
        </div>
      </div>

      <div class="form-group">
        <div class="col-xs-4 col-xs-offset-2">
          <a href="/holiday" class="btn btn-default">Cancel</a>
          <button type="submit" name="subSave" class="btn btn-primary">
            <i class="icon-plus"></i>
            Upload
          </button>
        </div>
      </div>
      
    </form>
  </div>
</div>