<div class="content-panel ">
    <h2 class="page-header">Create New Page</h2>
    <form class="form-horizontal" id="tableForm" name="tableForm" method="POST" action="/pages/add">
         <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Controller</label>
            <div class="col-xs-3">
                <input type="text" class="form-control" id="controller" name="controller" placeholder="Enter controller here.." required="">                
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Action</label>
            <div class="col-xs-3">
                <input type="text" class="form-control" id="action" name="action" placeholder="Enter action here.." required="">                
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Status</label>
            <div class="col-xs-3">
                <select name="status" required="">
                    <option value="ACTIVE">Active</option>
                    <option value="INACTIVE">Inactive</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Route</label>
            <div class="col-xs-3">
                <input type="text" class="form-control" id="route" name="route" placeholder="Enter route here.." >                
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Page Name</label>
            <div class="col-xs-3">
                <input type="text" class="form-control" id="pagename" name="pagename" placeholder="Enter page name here.." required="">                
            </div>
        </div>        
        <div class="col-lg-offset-2">
            <a href="/pages"  class="btn btn-default">Cancel </a>
            <input type="reset" value="Reset"  class="btn btn-default">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

<script>


    jQuery.validator.addMethod(
            "regexmeta",
            function(value, element, regexp) {
                var re = new RegExp('^[a-zA-Z0-9-_ ]+$');
                return this.optional(element) || re.test(value);
            },
            "Value should only be letters, numbers, underscore or hyphen only."
            );
	
        $("#tableForm").validate({
        errorClass: 'has-error',
        validClass: 'has-success',
        errorElement: 'span',
        highlight: function(element, errorClass, validClass) {
            $(element).parents("div.form-group").addClass(errorClass).removeClass(validClass);

        },
        unhighlight: function(element, errorClass, validClass) {
            $(element).parents(".form-group.has-error").removeClass(errorClass).addClass(validClass);
        },
        rules: {
            controller: {
                regexmeta: "dummy",
                maxlength: 100
            },
            action: {
                regexmeta: "dummy",
                maxlength: 100
            },
            route: {
                regexmeta: "dummy",
                maxlength: 100
            },
            pagename: {
                regexmeta: "dummy",
                maxlength: 100
            }

        }
    });
    
    </script>