<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\View\Helper\Authhelper'       => __DIR__ . '/view/helper/auth.php',
    'Application\View\Helper\Navhelper'        => __DIR__ . '/view/helper/nav.php',
    'Application\View\Helper\Breadcrumbhelper' => __DIR__ . '/view/helper/breadcrumb.php',
    'Application\View\Helper\LoggedUserhelper' => __DIR__ . '/view/helper/loggedUser.php',
    'Application\View\Helper\Confhelper'       => __DIR__ . '/view/helper/conf.php',

);
