<?php
$sessionManager = new \Zend\Session\SessionManager();
$sessionStorage = $sessionManager->getStorage();
$systemRole = $sessionStorage->getMetaData('role');
?>

<div class="content-panel ">
    <h2 class="page-header">Schedules - <?php echo $employee['first_name']. ' '.$employee['last_name']; ?></h2>

    <div class="page-content" style="">
        <div class="clearfix">
            <div id="get" class="form-search">
                <form id="search-form" method="get">        
                    <input id="pg-hidden" type="hidden" name="pg" value="1"/>                    
                    <input id="employee_id" type="hidden" name="employee_id" value="<?php echo $employee['id']; ?>"/>
                    <input id="role-hidden" type="hidden" name="role-hidden" value="<?php echo $systemRole; ?>"/>
                    <input id="sort-col-hidden" type="hidden" name="sortcol" value="id"/>
                    <input id="sort-val-hidden" type="hidden" name="sortval" value="ASC"/>
                    <input id="report-name-hidden" type="hidden" name="report-name-hidden" value="schedules"/>
                    
                    <?php if($employee['first_name'] != 'Not Found' && $systemRole == 'system-administrator') {?>
                    <a class="btn btn-primary pull-left" href="<?php echo '/schedules/add/'.$employee['id'] ; ?>" >
                        <i class="icon-plus"></i>
                        Add New Schedule
                    </a>
                    <?php } ?>
                </form>
            </div>
          
            <div class="pull-right" style="margin-top:-20px;">                

                <div id="pagination-div" class="clearfix">                    
                    <ul id="pagination-ul" class="pagination">                        
                    </ul>
                </div>
            </div>    
        </div>
        <div>
            <?php //var_dump($employee); ?>
        </div>

        <div class="wide-table">
            <table class="table table-striped table-hover">
                <thead id="search-thead">
                    <tr>
                        <th>
                        <!--<a class="sort-a" onclick="sortResultsBy('role')">Date Start ▼</a>-->
                        Date Start
                        </th>
                        <th>Date End</th>
                        <th>Time In</th>
                        <th>Time Out</th>
                        <th>Action</th>                        
                    </tr>
                </thead>
                <tbody id="search-tbody">
                </tbody>
            </table>  
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("#search-form").submit();
    });

$('input#search-text-input').bind('input', function() {
        var c = this.selectionStart,
                r = /[^a-z0-9 _]/gi,
                v = $(this).val();
        if (r.test(v)) {
            $(this).val(v.replace(r, ''));
            c--;
        }
        this.setSelectionRange(c, c);
    });
</script>

