<div class="content-panel ">
    <h2 class="page-header">Create New User</h2>
    
    <div class="page-content">

<div class="alert alert-info">
    Required Columns: username, password, pwd_exp_date, role
   
</div>

  <?php  if (!empty($data['saveMessages'])){
      echo ' <div class="alert alert-danger">';
      foreach($data['saveMessages'] as $message){
        echo "<li>$message</li>";
      }
      echo "</div>";
  }?>


  <form class="form-horizontal" id="tableForm" name="tableForm" method="POST" enctype="multipart/form-data" action="">
    <div class="form-group">
      <label for="file" class="col-xs-2 control-label">CSV File</label>
      <div class="col-xs-3">
        <input type="file" name="file" id="file" required><br>
      </div>
    </div>

    <div class="form-group">
      <div class="col-xs-4 col-xs-offset-2">
        <a href="/user" class="btn btn-default">Cancel</a>
        <button type="submit" name="subSave" class="btn btn-primary">
          <i class="icon-plus"></i>
          Upload
        </button>
      </div>
    </div>
    
  </form>
</div>
</div>