<div class="content-panel ">
    <h2 class="page-header">Users Accounts</h2>
    <div class="page-content" style="">
        <div class="clearfix">
            <div id="get" class="form-search">
                <form id="search-form" method="get">
                    <input id="pg-hidden" type="hidden" name="pg" value="1"/>
                    <input id="report-name-hidden" type="hidden" name="report-name-hidden" value="user"/>
                    <input id="sort-col-hidden" type="hidden" name="sortcol" value="username"/>
                    <input id="sort-val-hidden" type="hidden" name="sortval" value="ASC"/>
                    <a class="btn btn-primary pull-left" href="/user/add" style="margin-right:10px;">
                        <i class="icon-plus"></i>
                        Add New User
                    </a>
<!--                    <a class="btn btn-primary pull-left" href="/user/bulkadd" style="margin-right:10px;">
                        <i class="icon-plus"></i>
                        Add New Users in Bulk
                    </a>
                    <button type="button" data-toggle="modal" id="delete_button_all"  value="Delete Selected" class="btn btn-default pull-left">
                        <i class="icon-minus"></i>
                        Delete Selected
                    </button>-->
                    <div class="col-xs-3">
                        <div class="input-group">
                            <input id="search-text-input" type="user/search" name="search" placeholder="Search Text" class="form-control">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="icon-search"></i> Search</button>
                            </div><!-- /btn-group -->
                        </div><!-- /input-group -->
                    </div>
                </form>
            </div>
            <div class="pull-right" style="margin-top:-20px;">
                <div id="pagination-label"></div>
                <div id="pagination-div">
                    <ul id="pagination-ul" class="pagination">

                    </ul>
                </div>
            </div>
        </div>

        <div class="wide-table">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th><a class="sort-a" onclick="sortResultsBy('username')">Username ▼</a></th>
						<th><a class="sort-a" onclick="sortResultsBy('email')">Email ▼</a></th>
                        <th><a class="sort-a" onclick="sortResultsBy('pwd_exp_date')">Pwd Exp Date ▼</a></th>
                        <th><a class="sort-a" onclick="sortResultsBy('status')">Status ▼</a></th>
                        <th><a class="sort-a" onclick="sortResultsBy('role')">Role ▼</a></th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody id="search-tbody">
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="choose_dialog" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-body">
                <strong>Please select users to delete.</strong>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><strong>OK</strong></button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="confirmation_dialog" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><strong>Delete Confirmation</strong></h4>
            </div>
            <div class="modal-body">
                <strong>Continue deletion? This action is irrevocable.</strong>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="delete_btn"><strong>Delete</strong></button>
                <button type="button" class="btn btn-default" data-dismiss="modal"><strong>Cancel</strong></button>
            </div>
        </div>
    </div>
</div>

<form  action="/user/bulkdelete" method="POST" name="userdeleteform" id="userdeleteform">
    <input type="hidden" name="usernames" value="" id="usernames"/>
</form>

<script type="text/javascript">

    function checkDeleteUsers() {
        var usernames = "";
        $("input:checkbox[type=checkbox]:checked").each(function()
        {
            usernames = $(this).val() + ', ' + usernames;
        });
        if (usernames == "") {
            $("#choose_dialog").modal();
        } else {
            $("#confirmation_dialog").modal();
        }
    }

    $(document).ready(function() {
        $("#search-form").submit();
    });

    $("#delete_button_all").on('click', function() {
        checkDeleteUsers();
    });

    $("#delete_btn").on('click', function() {
        //$("#list_form").submit();
        var usernames = "";
        $("input:checkbox[type=checkbox]:checked").each(function()
        {
            usernames = $(this).val() + ', ' + usernames;
        });
        $("#usernames").val(usernames);
        $("#userdeleteform").submit();
    });
$('input#search-text-input').bind('input', function() {
        var c = this.selectionStart,
                r = /[^a-z0-9 _]/gi,
                v = $(this).val();
        if (r.test(v)) {
            $(this).val(v.replace(r, ''));
            c--;
        }
        this.setSelectionRange(c, c);
    });

</script>
