<div class="content-panel ">
    <h2 class="page-header">My Account</h2>
    <form class="form-horizontal" id="tableForm" name="tableForm" method="POST" action="/user/update">
        <div class="form-group">
            <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Username</label>
            <div class="col-xs-3">
                <h4><?php echo $user['username'] ?></h4>
            </div>
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Password Expiration</label>
            <div class="col-xs-3">
                <h4><?php echo substr($user['pwd_exp_date'], 0, -9); ?></h4>
            </div>
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Role</label>
            <div class="col-xs-3">
                <h4><?php echo $user->role; ?></h4>
            </div>
        </div>
            
        <div class="form-group">
            <label for="exampleInputEmail1" class="col-xs-2 control-label">Associated Employee</label>
            <div class="col-xs-3">
                <h4><?php echo $user->emp_display ?></h4>
            </div>
        </div>            

        <div class="col-lg-offset-2">
            <a href="/"  class="btn btn-primary">Back </a>
<!--            <button type="submit" class="btn btn-primary">Submit</button>-->
        </div>
    </form>
</div>

<?php
$conf = $this->Conf_widget();
?>


<script>
    $(function() {
        $("#pwd_exp_date_view").datepicker({
            dateFormat: 'yy-mm-dd',
        });

    });


    jQuery.validator.addMethod("notEqual", function(value, element, param) {
        return this.optional(element) || value != $(param).val();
    }, "Username and Password should be different");


    $("#tableForm").validate({
        errorClass: 'has-error',
        validClass: 'has-success',
        errorElement: 'span',
        highlight: function(element, errorClass, validClass) {
            $(element).parents("div.form-group").addClass(errorClass).removeClass(validClass);

        },
        unhighlight: function(element, errorClass, validClass) {
            $(element).parents(".form-group.has-error").removeClass(errorClass).addClass(validClass);
        },
        rules: {
            new_password: {
                minlength: <?php echo $conf['password_length']; ?>,
                notEqual: "#username"
            },
            password_confirm: {
                equalTo: "#new_password"
            }

        }
    });
</script>