
        <div id="main-wrapper" class="l-main-wrapper">

          <div class="container l-primary" id="primary">
            
            <div class="row content">
                


<div id="restricted" class="restricted">

  <i class="icon icon-exclamation-triangle"></i>
  
  <h1>Restricted</h1>
  <p>Sorry, you are not allowed to view this page. Please contact the system administrator.</p>
  <a href="/" class="btn btn-primary">Back to Dashboard</a>

</div>
            </div> <!-- /.row.content -->

          </div> <!-- /#primary -->
          
        </div>
        