<div class="content-panel ">
    <h2 class="page-header">System Configuration Options</h2>
    <div class="page-content" style="">
        <div class="clearfix">
            <div id="get" class="form-search">
                <form id="search-form" method="get">        
                    <input id="pg-hidden" type="hidden" name="pg" value="1"/>
                    <input id="report-name-hidden" type="hidden" name="report-name-hidden" value="options"/>
                    <input id="sort-col-hidden" type="hidden" name="sortcol" value="option_key"/>
                    <input id="sort-val-hidden" type="hidden" name="sortval" value="ASC"/>
                    <div class="col-xs-3">
                        <div class="input-group">
                            <input id="search-text-input" type="/options/search" name="search" placeholder="Search Text" class="form-control">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="icon-search"></i> Search</button>
                            </div><!-- /btn-group -->
                        </div><!-- /input-group -->
                    </div>
                </form>
            </div>
            <div class="pull-right" style="margin-top:-20px;">        
                <div id="pagination-label"></div>
                <div id="pagination-div">
                    <ul id="pagination-ul" class="pagination">

                    </ul>
                </div>
            </div>    
        </div>

        <div class="wide-table">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th><a class="sort-a" onclick="sortResultsBy('option_key')">Configuration▼</a></th>
                        <th><a class="sort-a" onclick="sortResultsBy('option_value')">Value▼</a></th>
                        <th><a class="sort-a" onclick="sortResultsBy('option_type')">Type▼</a></th>
                        <th><a class="sort-a" onclick="">Details</a></th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody id="search-tbody">
                </tbody>
            </table>  
        </div>
    </div>
</div>
<script>

    $(document).ready(function() {
        $("#search-form").submit();
    });

    /*
     $("input#search-text-input").on("keypress", function (e)
     {
     var re = new RegExp('^[a-zA-Z0-9 ]');
     if (!re.test(String.fromCharCode(e.which))) return false;
     }
     );
     */

    $('input#search-text-input').bind('input', function() {
        var c = this.selectionStart,
                r = /[^a-z0-9 _]/gi,
                v = $(this).val();
        if (r.test(v)) {
            $(this).val(v.replace(r, ''));
            c--;
        }
        this.setSelectionRange(c, c);
    });

</script>
